### ISSUE TITLE
Dialog not popping up...

### ISSUE THREAD

**Issue by johng1492** [tsjdev-apps/apptrackingtransparency-xf-demo#1]
Do you have a demo on how to get this to work with iOS 15? Good work. Thx

**Comment by tsjdev-apps** [comment]
Hi @johng1492,

sorry for the delay in answering your issue. You are right that the dialog wasn't shown on iOS15.
I've adjusted the code so it is working now on iOS15 again. Before calling `ATTrackingManager.RequestTrackingAuthorization` we need to wait a little bit. This was achieve by adding a `Task.Delay`. Now the dialog is showing on iOS15.
